### ISSUE TITLE
How to remove plus(+) sign from encryption. 

### ISSUE THREAD

**Issue by mohdbashir** [nickcv-ln/yii2-encrypter#1]
My encrytion for value "2" is "vURoRv4D6OxzgIH3KXH+uA==" having + symbol. which is creating a problem.
Please suggest to stop + symbol in URL.

**Comment by nickcv-ln** [comment]
you could base64_decode it but that string may actually give you more troubles. What you should probably be doing is url_encoding the string and decode it if you need it in a URL.

I don't believe you can remove plus signs from base64 encoding.
